language: go

go:
  - master # This uses automatically the latest version of go

install:  
  - wget -O /tmp/hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.61.0/hugo_0.61.0_Linux-64bit.deb
  - sudo dpkg -i /tmp/hugo.deb
# the below is failing on TravisCI all of a sudden?
#install:
#  - go get github.com/gohugoio/hugo # This provides the latest version of Hugo to Travis CI

script:
  - hugo # This commands builds your website on travis

deploy:
  local_dir: public # Default static site output dir for Hugo
  repo: mrbarge/blog # This is the slug of the repo you want to deploy your site to
  target_branch: master # GitHub pages branch to deploy to (in other cases it can be gh-pages)
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # This is the authentication which you will setup in the next step in travis-ci dashboard
  email: mrbarge-site-bot@users.noreply.github.com
  name: "mrbarge site bot"
  on:
    branch: master